[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Compresso"
version = "0.1.0"
authors = [ { name = "Rob Webb" } ]
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["src"]